name-template: '$RESOLVED_VERSION 🌈'
tag-template: '$RESOLVED_VERSION'
prerelease: true
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'framework'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    label:
      - 'chore'
      - 'dependencies'
      - 'tech-debt'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: minor
exclude-labels:
  - 'skip-changelog'
template: |
  ## Changes

  $CHANGES