---
changelog:
  exclude:
    authors:
      - github-actions
  categories:
    - title: Breaking Changes 🚨
      labels:
        - major
        - integration
    - title: Bug Fixes 🐞
      labels:
        - bug
    - title: New Features ✨
      labels:
        - feature
    - title: Improvements 🛠
      labels:
        - enhancement
        - improvement
        - framework
    - title: Security 🔒
      labels:
        - security
    - title: Documentation 📚
      labels:
        - documentation
    - title: Build, Package, Deploy 📦
      labels:
        - dependencies
        - BPD
    - title: Automation and Testing 🚦
      labels:
        - CI/CD
        - test-only
    - title: Other Changes ⚙️
      labels:
        - "*"
