# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: all
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
ENABLE:
  - ACTION
  - DOCKERFILE
  - XML
  - YAML
  - JSON
  - KUBERNETES
ENABLE_LINTERS:
  - BASH_EXEC
  - JSON_PRETTIER
  - DOCKERFILE_HADOLINT
  - XML_XMLLINT
  - YAML_PRETTIER
  - YAML_YAMLLINT
  - ACTION_ACTIONLINT
  - KUBERNETES_HELM
PRINT_ALL_FILES: false
DOCKERFILE_HADOLINT_FILE_NAME: ../../contrib/docker/.hadolint.yaml
YAML_FILTER_REGEX_EXCLUDE: .*contrib/helm.*
KUBERNETES_FILTER_REGEX_INCLUDE: .*contrib/helm.*
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
SHOW_ELAPSED_TIME: true
FLAVOR_SUGGESTIONS: false
EMAIL_REPORTER: false
FILEIO_REPORTER: false
JSON_REPORTER: true
GITHUB_STATUS_REPORTER: false
GITHUB_COMMENT_REPORTER: false
