version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-cluster-8
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
    hostname: elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.2
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elastic
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.3.2
    container_name: filebeat
    command: filebeat -e -strict.perms=false
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    volumes:
      - ${PWD}/contrib/elasticsearch/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - $PWD:/app
    networks:
      - elastic
    depends_on:
      - elasticsearch
      - kibana

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.3.2
    container_name: metricbeat
    command: metricbeat -e -strict.perms=false
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    volumes:
      - metricbeat-data:/usr/share/metricbeat/data
      - ./contrib/elasticsearch/metricbeat/agents-metricbeat.yml:/usr/share/metricbeat/modules.d/metricbeat-agents.yml:ro
    networks:
      - elastic
    depends_on:
      - elasticsearch
      - kibana

volumes:
  es-data:
    driver: local
  metricbeat-data:
    driver: local

networks:
  elastic:
    driver: bridge
