---
filebeat.inputs:
  - type: log
    paths: /var/log/emissary/*.json
    json.keys_under_root: true
    json.overwrite_keys: true

output.elasticsearch:
  index: "emissary-test-%{[agent.version]}-%{+yyyy.MM.dd}"
  hosts: "https://elasticsearch:9200"
  username: "elastic"
  password: "${ESPASSWORD}"
  ssl.verification_mode: none
  ssl.certificate: "/etc/tls/http_ca.crt"
  ssl.key: "/etc/tls/http.key.pem"

setup.template:
  name: "emissary-test"
  pattern: "emissary-test-*"
