name: "Cherry pick commit(s) to a branch"

on:
  workflow_dispatch:
    inputs:
      cherrypick_commits:
        description: "List of space delimited commits to cherry pick"
        required: false
        default: ""

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check for protected branch
        if: ${{ github.ref_name == 'master' }}
        run: |
          echo "Cannot cherry pick to protected branch"
          exit 1
      - name: Check for commit(s)
        if: ${{ github.event.inputs.cherrypick_commits == '' }}
        run: |
          echo "No commits specified to cherry pick"
          exit 1

  cherrypick:
    needs: verify
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.3.0

      - name: Cherry pick to patch branch
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git fetch --all
          git cherry-pick ${{ github.event.inputs.cherrypick_commits }}
          git push -u origin ${{ github.ref_name }}