name: Measure Code Coverage

on:
  pull_request:

jobs:
  build:
    name: Java build with code coverage
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B --no-transfer-progress verify -Dcode-quality --file pom.xml

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.EMISSARY_GITHUB_TOKEN }}
          min-coverage-overall: 50
          min-coverage-changed-files: 80

      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"