name: Measure Code Coverage

on:
  pull_request:

jobs:
  build:
    name: Java build with code coverage
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          cache: 'maven'
          distribution: 'corretto'
      - name: Build with Maven
        run: mvn -B --no-transfer-progress verify -Dcode-quality --file pom.xml

      - name: Publish test coverage results
        uses: PavanMudigonda/jacoco-reporter@v4.5
        with:
          coverage_results_path: 'target/site/jacoco/jacoco.xml'
          coverage_report_title: 'Test coverage results'
          coverage_report_name: 'Test coverage results'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 50
          fail_below_threshold: true