---
name: Lint Codebase

on: # yamllint disable-line rule:truthy
  push:
    branches: [main, release/**, patch/**]
  pull_request:
    branches: [main, release/**, patch/**]

permissions:
  contents: read
  statuses: write

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: oxsecurity/megalinter@v7
        env:
          LOG_LEVEL: NOTICE
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXTENDS: .github/linters/.mega-linter.yml
          # setting this to false means that only changed files will be scanned in each commit
          VALIDATE_ALL_CODEBASE: ${{ github.event_name != 'pull_request' }}
