name: Java CI with Maven

on: # yamllint disable-line rule:truthy
  push:
    branches: [master, release/**, patch/**]
  pull_request:
    branches: [master, release/**, patch/**]

jobs:
  build:

    name: Standard build on Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['11']
        experimental: [false]
        include:
          - java: '15'
            experimental: true
          - java: '16'
            experimental: true
          - java: '17'
            experimental: true
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.3.0

      - name: Configure Java & Maven
        uses: actions/setup-java@v3
        with:
          java-version: '${{ matrix.java }}'
          cache: 'maven'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn -B -e -ntp "-Dstyle.color=always" verify

      - name: Verify Changed Files
        run: contrib/ci/detect-changes.sh
