---
name: Mega Lint Codebase

on:
  push:
    branches: [master, release/**, patch/**]
  pull_request:
    branches: [master, release/**, patch/**]

permissions:
  contents: read
  statuses: write

jobs:
  super-linter:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: oxsecurity/megalinter@v7
        env:
          LOG_LEVEL: NOTICE
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # setting this to false means that only changed files will be scanned in each commit
          VALIDATE_ALL_CODEBASE: ${{ github.event_name != 'pull_request' }}
          # Enable Linters to run
          VALIDATE_GITHUB_ACTIONS: true
          # VALIDATE_GOOGLE_JAVA_FORMAT: true
          JAVA_FILE_NAME: ../../contrib/checkstyle.xml
          VALIDATE_DOCKERFILE_HADOLINT: true
          DOCKERFILE_HADOLINT_FILE_NAME: ../../contrib/docker/.hadolint.yaml
          # VALIDATE_MARKDOWN: true
          VALIDATE_XML: true
          VALIDATE_YAML: true
          FILTER_REGEX_EXCLUDE: .*contrib/helm.*
          GITHUB_COMMENT_REPORTER: false
