name: Publish package to Multipass Nexus
on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch To Publish"
        default: "master"
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: | 
            [{
              "id": "multipass-release"
              "username": "${{ secrets.multipass_username }}"
              "password": "${{ secrets.multipass_password }}"
            }]
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Publish package
        run: mvn -B deploy -DskipFormat -Duser.timezone=GMT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}