name: Publish package to Multipass Nexus
on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      branch:
        description: "Package Branch"
        default: "master"
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Publish package
        run: mvn -B deploy --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}